import { createStore } from "vuex";

export default createStore({
    state: {
        senators: [
            {
                address1: "709 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "B001230",
                eliteSchool: true, //Smith
                email: "baldwin.senate.gov/feedback",
                firstName: "Tammy",
                lastName: "Baldwin",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5653",
                portrait: "wi-tammy-baldwin",
                senateClass: "Class I",
                state: "Wisconsin",
                website: "baldwin.senate.gov",
            },
            {
                address1: "307 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "June 25, 2007",
                bioguideId: "B001261",
                eliteSchool: true, //Georgetown
                email: "barrasso.senate.gov/public/index.cfm/contact-form",
                firstName: "John",
                lastName: "Barrasso",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6441",
                portrait: "wy-john-barrasso",
                senateClass: "Class I",
                state: "Wyoming",
                website: "barrasso.senate.gov",
            },
            {
                address1: "261 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 21, 2009",
                bioguideId: "B001267",
                eliteSchool: true, //Yale
                email: "bennet.senate.gov/public/index.cfm/contact",
                firstName: "Michael F.",
                lastName: "Bennet",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5852",
                portrait: "co-michael-bennet",
                senateClass: "Class III",
                state: "Colorado",
                website: "bennet.senate.gov",
            },
            {
                address1: "357 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "B001243",
                eliteSchool: false,
                email: "blackburn.senate.gov/email-me",
                firstName: "Marsha",
                lastName: "Blackburn",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3344",
                portrait: "tn-marsha-blackburn",
                senateClass: "Class I",
                state: "Tennessee",
                website: "blackburn.senate.gov",
            },
            {
                address1: "706 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B001277",
                eliteSchool: true, //Harvard, Yale
                email: "blumenthal.senate.gov/contact",
                firstName: "Richard",
                lastName: "Blumenthal",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2823",
                portrait: "ct-richard-blumenthal",
                senateClass: "Class III",
                state: "Connecticut",
                website: "blumenthal.senate.gov",
            },
            {
                address1: "260 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B000575",
                eliteSchool: false,
                email: "blunt.senate.gov/public/index.cfm/contact-roy",
                firstName: "Roy",
                lastName: "Blunt",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5721",
                portrait: "mo-roy-blunt",
                senateClass: "Class III",
                state: "Missouri",
                website: "blunt.senate.gov",
            },
            {
                address1: "717 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "October 31, 2013",
                bioguideId: "B001288",
                eliteSchool: true, //Stanford, Oxford, Yale
                email: "booker.senate.gov/?p=contact",
                firstName: "Cory A.",
                lastName: "Booker",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3224",
                portrait: "nj-cory-booker",
                senateClass: "Class II",
                state: "New Jersey",
                website: "booker.senate.gov",
            },
            {
                address1: "141 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B001236",
                eliteSchool: false,
                email: "boozman.senate.gov/public/index.cfm/contact",
                firstName: "John",
                lastName: "Boozman",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4843",
                portrait: "ar-john-boozman",
                senateClass: "Class III",
                state: "Arkansas",
                website: "boozman.senate.gov",
            },
            {
                address1: "404 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "B001310",
                eliteSchool: true, //Harvard
                email: "braun.senate.gov/contact-mike",
                firstName: "Mike",
                lastName: "Braun",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4814",
                portrait: "in-mike-braun",
                senateClass: "Class I",
                state: "Indiana",
                website: "braun.senate.gov",
            },
            {
                address1: "503 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "B000944",
                eliteSchool: true, //Yale
                email: "brown.senate.gov/contact",
                firstName: "Sherrod",
                lastName: "Brown",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2315",
                portrait: "oh-sherrod-brown",
                senateClass: "Class I",
                state: "Ohio",
                website: "brown.senate.gov",
            },
            {
                address1: "217 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2005",
                bioguideId: "B001135",
                eliteSchool: false,
                email: "burr.senate.gov/contact",
                firstName: "Richard",
                lastName: "Burr",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3154",
                portrait: "nc-richard-burr",
                senateClass: "Class III",
                state: "North Carolina",
                website: "burr.senate.gov",
            },
            {
                address1: "511 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "C000127",
                eliteSchool: false,
                email: "cantwell.senate.gov/public/index.cfm/email-maria",
                firstName: "Maria",
                lastName: "Cantwell",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3441",
                portrait: "wa-maria-cantwell",
                senateClass: "Class I",
                state: "Washington",
                website: "cantwell.senate.gov",
            },
            {
                address1: "172 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001047",
                eliteSchool: true, //Duke
                email: "capito.senate.gov/contact/contact-shelley",
                firstName: "Shelley Moore",
                lastName: "Capito",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6472",
                portrait: "wv-shelley-moore-capito",
                senateClass: "Class II",
                state: "West Virginia",
                website: "capito.senate.gov",
            },
            {
                address1: "509 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "C000141",
                eliteSchool: false,
                email: "cardin.senate.gov/contact",
                firstName: "Benjamin L.",
                lastName: "Cardin",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4524",
                portrait: "md-benjamin-cardin",
                senateClass: "Class I",
                state: "Maryland",
                website: "cardin.senate.gov",
            },
            {
                address1: "513 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "C000174",
                eliteSchool: false,
                email: "carper.senate.gov/public/index.cfm/email-senator-carper",
                firstName: "Thomas R.",
                lastName: "Carper",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2441",
                portrait: "de-thomas-carper",
                senateClass: "Class I",
                state: "Delaware",
                website: "carper.senate.gov",
            },
            {
                address1: "393 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "C001070",
                eliteSchool: false,
                email: "casey.senate.gov/contact",
                firstName: "Robert P.",
                lastName: "Casey, Jr.",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6324",
                portrait: "pa-robert-casey",
                senateClass: "Class I",
                state: "Pennsylvania",
                website: "casey.senate.gov",
            },
            {
                address1: "520 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001075",
                eliteSchool: false,
                email: "cassidy.senate.gov/contact",
                firstName: "Bill",
                lastName: "Cassidy",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5824",
                portrait: "la-bill-cassidy",
                senateClass: "Class II",
                state: "Louisiana",
                website: "cassidy.senate.gov",
            },
            {
                address1: "413 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "C001035",
                eliteSchool: false,
                email: "collins.senate.gov/contact",
                firstName: "Susan M.",
                lastName: "Collins",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2523",
                portrait: "me-susan-collins",
                senateClass: "Class II",
                state: "Maine",
                website: "collins.senate.gov",
            },
            {
                address1: "218 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 15, 2010",
                bioguideId: "C001088",
                eliteSchool: true, //Amherst, Yale
                email: "coons.senate.gov/contact",
                firstName: "Christopher A.",
                lastName: "Coons",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5042",
                portrait: "de-christopher-coons",
                senateClass: "Class II",
                state: "Delaware",
                website: "coons.senate.gov",
            },
            {
                address1: "517 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 2, 2002",
                bioguideId: "C001056",
                eliteSchool: false,
                email: "cornyn.senate.gov/contact",
                firstName: "John",
                lastName: "Cornyn",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2934",
                portrait: "tx-john-cornyn",
                senateClass: "Class II",
                state: "Texas",
                website: "cornyn.senate.gov",
            },
            {
                address1: "313 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "C001113",
                eliteSchool: false,
                email: "cortezmasto.senate.gov/contact",
                firstName: "Catherine",
                lastName: "Cortez Masto",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3542",
                portrait: "nv-catherine-cortez-masto",
                senateClass: "Class III",
                state: "Nevada",
                website: "cortezmasto.senate.gov",
            },
            {
                address1: "326 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001095",
                eliteSchool: true, //Harvard
                email: "cotton.senate.gov/contact/contact-tom",
                firstName: "Tom",
                lastName: "Cotton",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2353",
                portrait: "ar-tom-cotton",
                senateClass: "Class II",
                state: "Arkansas",
                website: "cotton.senate.gov",
            },
            {
                address1: "330 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "C001096",
                eliteSchool: false,
                email: "cramer.senate.gov/contact/contact-kevin",
                firstName: "Kevin",
                lastName: "Cramer",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2043",
                portrait: "nd-kevin-cramer",
                senateClass: "Class I",
                state: "North Dakota",
                website: "cramer.senate.gov",
            },
            {
                address1: "239 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1999",
                bioguideId: "C000880",
                eliteSchool: true, //Harvard
                email: "crapo.senate.gov/contact",
                firstName: "Mike",
                lastName: "Crapo",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6142",
                portrait: "id-mike-crapo",
                senateClass: "Class III",
                state: "Idaho",
                website: "crapo.senate.gov",
            },
            {
                address1: "127A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "C001098",
                eliteSchool: true, //Princeton, Harvard
                email: "cruz.senate.gov/?p=form&id=16",
                firstName: "Ted",
                lastName: "Cruz",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5922",
                portrait: "tx-ted-cruz",
                senateClass: "Class I",
                state: "Texas",
                website: "cruz.senate.gov",
            },
            {
                address1: "320 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "D000618",
                eliteSchool: false,
                email: "daines.senate.gov/connect/email-steve",
                firstName: "Steve",
                lastName: "Daines",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2651",
                portrait: "mt-steve-daines",
                senateClass: "Class II",
                state: "Montana",
                website: "daines.senate.gov",
            },
            {
                address1: "524 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "D000622",
                eliteSchool: false,
                email: "duckworth.senate.gov/content/contact-senator",
                firstName: "Tammy",
                lastName: "Duckworth",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2854",
                portrait: "il-tammy-duckworth",
                senateClass: "Class III",
                state: "Illinois",
                website: "duckworth.senate.gov",
            },
            {
                address1: "711 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "D000563",
                eliteSchool: true, //Georgetown
                email: "durbin.senate.gov/contact",
                firstName: "Richard J.",
                lastName: "Durbin",
                leadershipPosition: "Majority Whip",
                party: "D",
                phone: "(202) 224-2152",
                portrait: "il-richard-durbin",
                senateClass: "Class II",
                state: "Illinois",
                website: "durbin.senate.gov",
            },
            {
                address1: "730 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "E000295",
                eliteSchool: false,
                email: "ernst.senate.gov/public/index.cfm/contact",
                firstName: "Joni",
                lastName: "Ernst",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3254",
                portrait: "ia-joni-ernst",
                senateClass: "Class II",
                state: "Iowa",
                website: "ernst.senate.gov",
            },
            {
                address1: "331 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 10, 1992",
                bioguideId: "F000062",
                eliteSchool: true, //Stanford
                email: "feinstein.senate.gov/public/index.cfm/e-mail-me",
                firstName: "Dianne",
                lastName: "Feinstein",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3841",
                portrait: "ca-dianne-feinstein",
                senateClass: "Class I",
                state: "California",
                website: "feinstein.senate.gov",
            },
            {
                address1: "454 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "F000463",
                eliteSchool: false,
                email: "fischer.senate.gov/public/index.cfm/contact",
                firstName: "Deb",
                lastName: "Fischer",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6551",
                portrait: "ne-deb-fischer",
                senateClass: "Class I",
                state: "Nebraska",
                website: "fischer.senate.gov",
            },
            {
                address1: "478 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 26, 2009",
                bioguideId: "G000555",
                eliteSchool: true, //Dartmouth
                email: "gillibrand.senate.gov/contact/email-me",
                firstName: "Kirsten E.",
                lastName: "Gillibrand",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4451",
                portrait: "ny-kirsten-gillibrand",
                senateClass: "Class I",
                state: "New York",
                website: "gillibrand.senate.gov",
            },
            {
                address1: "290 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2003",
                bioguideId: "G000359",
                eliteSchool: false,
                email: "lgraham.senate.gov/public/index.cfm/e-mail-senator-graham",
                firstName: "Lindsey",
                lastName: "Graham",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5972",
                portrait: "sc-lindsey-graham",
                senateClass: "Class II",
                state: "South Carolina",
                website: "lgraham.senate.gov",
            },
            {
                address1: "135 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1981",
                bioguideId: "G000386",
                eliteSchool: false,
                email: "grassley.senate.gov/contact",
                firstName: "Chuck",
                lastName: "Grassley",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3744",
                portrait: "ia-chuck-grassley",
                senateClass: "Class III",
                state: "Iowa",
                website: "grassley.senate.gov",
            },
            {
                address1: "248 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "H000601",
                eliteSchool: false,
                email: "hagerty.senate.gov/email-me",
                firstName: "Bill",
                lastName: "Hagerty",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4944",
                portrait: "tn-bill-hagerty",
                senateClass: "Class II",
                state: "Tennessee",
                website: "hagerty.senate.gov",
            },
            {
                address1: "324 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "H001076",
                eliteSchool: true, //Brown
                email: "hassan.senate.gov/content/contact-senator",
                firstName: "Margaret Wood",
                lastName: "Hassan",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3324",
                portrait: "nh-maggie-hassan",
                senateClass: "Class III",
                state: "New Hampshire",
                website: "hassan.senate.gov",
            },
            {
                address1: "115 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "H001089",
                eliteSchool: true, //Stanford, Yale
                email: "hawley.senate.gov/contact-senator-hawley",
                firstName: "Josh",
                lastName: "Hawley",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6154",
                portrait: "mo-josh-hawley",
                senateClass: "Class I",
                state: "Missouri",
                website: "hawley.senate.gov",
            },
            {
                address1: "303 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "H001046",
                eliteSchool: false,
                email: "heinrich.senate.gov/contact",
                firstName: "Martin",
                lastName: "Heinrich",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5521",
                portrait: "nm-martin-heinrich",
                senateClass: "Class I",
                state: "New Mexico",
                website: "heinrich.senate.gov",
            },
            {
                address1: "374 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "H000273",
                eliteSchool: false,
                email: "hickenlooper.senate.gov/contact",
                firstName: "John W.",
                lastName: "Hickenlooper",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5941",
                portrait: "co-john-hickenlooper",
                senateClass: "Class II",
                state: "Colorado",
                website: "hickenlooper.senate.gov",
            },
            {
                address1: "109 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "H001042",
                eliteSchool: true, //Georgetown
                email: "hirono.senate.gov/contact",
                firstName: "Mazie K.",
                lastName: "Hirono",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6361",
                portrait: "hi-mazie-hirono",
                senateClass: "Class I",
                state: "Hawaii",
                website: "hirono.senate.gov",
            },
            {
                address1: "338 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "H001061",
                eliteSchool: true, //Dartmouth, Northwestern
                email: "hoeven.senate.gov/public/index.cfm/email-the-senator",
                firstName: "John",
                lastName: "Hoeven",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2551",
                portrait: "nd-john-hoeven",
                senateClass: "Class III",
                state: "North Dakota",
                website: "hoeven.senate.gov",
            },
            {
                address1: "702 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "April 9, 2018",
                bioguideId: "H001079",
                eliteSchool: false,
                email: "hydesmith.senate.gov/content/contact-senator",
                firstName: "Cindy",
                lastName: "Hyde-Smith",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5054",
                portrait: "ms-cindy-hyde-smith",
                senateClass: "Class II",
                state: "Mississippi",
                website: "hydesmith.senate.gov",
            },
            {
                address1: "205 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 16, 1994",
                bioguideId: "I000024",
                eliteSchool: false,
                email: "inhofe.senate.gov/contact",
                firstName: "James M.",
                lastName: "Inhofe",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4721",
                portrait: "ok-james-inhofe",
                senateClass: "Class II",
                state: "Oklahoma",
                website: "inhofe.senate.gov",
            },
            {
                address1: "328 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "J000293",
                eliteSchool: false,
                email: "ronjohnson.senate.gov/public/index.cfm/email-the-senator",
                firstName: "Ron",
                lastName: "Johnson",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5323",
                portrait: "wi-ron-johnson",
                senateClass: "Class III",
                state: "Wisconsin",
                website: "ronjohnson.senate.gov",
            },
            {
                address1: "231 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "K000384",
                eliteSchool: true, //Harvard
                email: "kaine.senate.gov/contact",
                firstName: "Tim",
                lastName: "Kaine",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4024",
                portrait: "va-tim-kaine",
                senateClass: "Class I",
                state: "Virginia",
                website: "kaine.senate.gov",
            },
            {
                address1: "516 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 2, 2020",
                bioguideId: "K000377",
                eliteSchool: false,
                email: "kelly.senate.gov",
                firstName: "Mark",
                lastName: "Kelly",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2235",
                portrait: "az-mark-kelly",
                senateClass: "Class III",
                state: "Arizona",
                website: "kelly.senate.gov",
            },
            {
                address1: "416 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "K000393",
                eliteSchool: false,
                email: "kennedy.senate.gov/public/email-me",
                firstName: "John",
                lastName: "Kennedy",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4623",
                portrait: "la-john-kennedy",
                senateClass: "Class III",
                state: "Louisiana",
                website: "kennedy.senate.gov",
            },
            {
                address1: "133 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "K000383",
                eliteSchool: true, //Dartmouth
                email: "king.senate.gov/contact",
                firstName: "Angus S.",
                lastName: "King, Jr.",
                leadershipPosition: null,
                party: "I",
                phone: "(202) 224-5344",
                portrait: "me-angus-king",
                senateClass: "Class I",
                state: "Maine",
                website: "king.senate.gov",
            },
            {
                address1: "425 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "K000367",
                eliteSchool: true, //Yale, Univ of Chicago
                email: "klobuchar.senate.gov/public/index.cfm/contact",
                firstName: "Amy",
                lastName: "Klobuchar",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3244",
                portrait: "mn-amy-klobuchar",
                senateClass: "Class I",
                state: "Minnesota",
                website: "klobuchar.senate.gov",
            },
            {
                address1: "316 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "L000575",
                eliteSchool: false,
                email: "lankford.senate.gov/contact/email",
                firstName: "James",
                lastName: "Lankford",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5754",
                portrait: "ok-james-lankford",
                senateClass: "Class III",
                state: "Oklahoma",
                website: "lankford.senate.gov",
            },
            {
                address1: "437 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1975",
                bioguideId: "L000174",
                eliteSchool: true, //Georgetown
                email: "leahy.senate.gov/contact",
                firstName: "Patrick J.",
                lastName: "Leahy",
                leadershipPosition: "President Pro Tempore",
                party: "D",
                phone: "(202) 224-4242",
                portrait: "vt-patrick-leahy",
                senateClass: "Class III",
                state: "Vermont",
                website: "leahy.senate.gov",
            },
            {
                address1: "361A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "L000577",
                eliteSchool: false,
                email: "lee.senate.gov/public/index.cfm/contact",
                firstName: "Mike",
                lastName: "Lee",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5444",
                portrait: "ut-mike-lee",
                senateClass: "Class III",
                state: "Utah",
                website: "lee.senate.gov",
            },
            {
                address1: "498 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "L000570",
                eliteSchool: false,
                email: "lujan.senate.gov/contact",
                firstName: "Ben Ray",
                lastName: "Luján",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6621",
                portrait: "nm-ben-ray-lujan",
                senateClass: "Class II",
                state: "New Mexico",
                website: "lujan.senate.gov",
            },
            {
                address1: "124 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "L000571",
                eliteSchool: false,
                email: "lummis.senate.gov/contact/contact-form/",
                firstName: "Cynthia M.",
                lastName: "Lummis",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3424",
                portrait: "wy-cynthia-lummis",
                senateClass: "Class II",
                state: "Wyoming",
                website: "lummis.senate.gov",
            },
            {
                address1: "306 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 15, 2010",
                bioguideId: "M001183",
                eliteSchool: false,
                email: "manchin.senate.gov/public/index.cfm/contact-form",
                firstName: "Joe",
                lastName: "Manchin, III",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3954",
                portrait: "wv-joe-manchin",
                senateClass: "Class I",
                state: "West Virginia",
                website: "manchin.senate.gov",
            },
            {
                address1: "255 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "July 16, 2013",
                bioguideId: "M000133",
                eliteSchool: false,
                email: "markey.senate.gov/contact",
                firstName: "Edward J.",
                lastName: "Markey",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2742",
                portrait: "ma-ed-markey",
                senateClass: "Class II",
                state: "Massachusetts",
                website: "markey.senate.gov",
            },
            {
                address1: "479A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "M001198",
                eliteSchool: false,
                email: "marshall.senate.gov/contact",
                firstName: "Roger",
                lastName: "Marshall",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4774",
                portrait: "ks-roger-marshall",
                senateClass: "Class II",
                state: "Kansas",
                website: "marshall.senate.gov",
            },
            {
                address1: "317 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1985",
                bioguideId: "M000355",
                eliteSchool: false,
                email: "mcconnell.senate.gov/public/index.cfm?p=contact",
                firstName: "Mitch",
                lastName: "McConnell",
                leadershipPosition: "Republican Leader",
                party: "R",
                phone: "(202) 224-2541",
                portrait: "ky-mitch-mcconnell",
                senateClass: "Class II",
                state: "Kentucky",
                website: "mcconnell.senate.gov",
            },
            {
                address1: "528 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 17, 2006",
                bioguideId: "M000639",
                eliteSchool: false,
                email: "menendez.senate.gov/contact",
                firstName: "Robert",
                lastName: "Menendez",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4744",
                portrait: "nj-robert-menendez",
                senateClass: "Class I",
                state: "New Jersey",
                website: "menendez.senate.gov",
            },
            {
                address1: "531 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "M001176",
                eliteSchool: true, //Stanford, Princeton
                email: "merkley.senate.gov/contact",
                firstName: "Jeff",
                lastName: "Merkley",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3753",
                portrait: "or-jeff-merkley",
                senateClass: "Class II",
                state: "Oregon",
                website: "merkley.senate.gov",
            },
            {
                address1: "521 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "M000934",
                eliteSchool: false,
                email: "moran.senate.gov/public/index.cfm/e-mail-jerry",
                firstName: "Jerry",
                lastName: "Moran",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6521",
                portrait: "ks-jerry-moran",
                senateClass: "Class III",
                state: "Kansas",
                website: "moran.senate.gov",
            },
            {
                address1: "522 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 20, 2002",
                bioguideId: "M001153",
                eliteSchool: true, //Georgetown
                email: "murkowski.senate.gov/public/index.cfm/contact",
                firstName: "Lisa",
                lastName: "Murkowski",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6665",
                portrait: "ak-lisa-murkowski",
                senateClass: "Class III",
                state: "Alaska",
                website: "murkowski.senate.gov",
            },
            {
                address1: "136 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "M001169",
                eliteSchool: true, //Williams
                email: "murphy.senate.gov/contact",
                firstName: "Christopher",
                lastName: "Murphy",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4041",
                portrait: "ct-christopher-murphy",
                senateClass: "Class I",
                state: "Connecticut",
                website: "murphy.senate.gov",
            },
            {
                address1: "154 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1993",
                bioguideId: "M001111",
                eliteSchool: false,
                email: "murray.senate.gov/write-to-patty/",
                firstName: "Patty",
                lastName: "Murray",
                leadershipPosition: "Assistant Democratic Leader",
                party: "D",
                phone: "(202) 224-2621",
                portrait: "wa-patty-murray",
                senateClass: "Class III",
                state: "Washington",
                website: "murray.senate.gov",
            },
            {
                address1: "455 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "O000174",
                eliteSchool: true, //Georgetown, London School of Econ
                email: "ossoff.senate.gov/contact-us/",
                firstName: "Jon",
                lastName: "Ossoff",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3521",
                portrait: "ga-jon-ossoff",
                senateClass: "Class II",
                state: "Georgia",
                website: "ossoff.senate.gov",
            },
            {
                address1: "112 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "P000145",
                eliteSchool: true, //MIT
                email: "padilla.senate.gov/contact",
                firstName: "Alex",
                lastName: "Padilla",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3553",
                portrait: "ca-alex-padilla",
                senateClass: "Class III",
                state: "California",
                website: "padilla.senate.gov",
            },
            {
                address1: "167 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "P000603",
                eliteSchool: true, //Duke
                email: "paul.senate.gov/connect/email-rand",
                firstName: "Rand",
                lastName: "Paul",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4343",
                portrait: "ky-rand-paul",
                senateClass: "Class III",
                state: "Kentucky",
                website: "paul.senate.gov",
            },
            {
                address1: "724 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "P000595",
                eliteSchool: false,
                email: "peters.senate.gov/contact/email-gary",
                firstName: "Gary C.",
                lastName: "Peters",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6221",
                portrait: "mi-gary-peters",
                senateClass: "Class II",
                state: "Michigan",
                website: "peters.senate.gov",
            },
            {
                address1: "448 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "P000449",
                eliteSchool: true, //Dartmouth
                email: "portman.senate.gov/public/index.cfm/contact?p=contact-form",
                firstName: "Rob",
                lastName: "Portman",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3353",
                portrait: "oh-rob-portman",
                senateClass: "Class III",
                state: "Ohio",
                website: "portman.senate.gov",
            },
            {
                address1: "728 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "R000122",
                eliteSchool: true, //West Point, Harvard
                email: "reed.senate.gov/contact",
                firstName: "Jack",
                lastName: "Reed",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4642",
                portrait: "ri-jack-reed",
                senateClass: "Class II",
                state: "Rhode Island",
                website: "reed.senate.gov",
            },
            {
                address1: "483 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "R000584",
                eliteSchool: false,
                email: "risch.senate.gov/public/index.cfm?p=Email",
                firstName: "James E.",
                lastName: "Risch",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2752",
                portrait: "id-james-risch",
                senateClass: "Class II",
                state: "Idaho",
                website: "risch.senate.gov",
            },
            {
                address1: "354 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "R000615",
                eliteSchool: true, //Harvard
                email: "romney.senate.gov/contact-senator-romney",
                firstName: "Mitt",
                lastName: "Romney",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5251",
                portrait: "ut-mitt-romney",
                senateClass: "Class I",
                state: "Utah",
                website: "romney.senate.gov",
            },
            {
                address1: "713 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "R000608",
                eliteSchool: false,
                email: "rosen.senate.gov/contact_jacky",
                firstName: "Jacky",
                lastName: "Rosen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6244",
                portrait: "nv-jacky-rosen",
                senateClass: "Class I",
                state: "Nevada",
                website: "rosen.senate.gov",
            },
            {
                address1: "716 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "R000605",
                eliteSchool: false,
                email: "rounds.senate.gov/contact/email-mike",
                firstName: "Mike",
                lastName: "Rounds",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5842",
                portrait: "sd-mike-rounds",
                senateClass: "Class II",
                state: "South Dakota",
                website: "rounds.senate.gov",
            },
            {
                address1: "284 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "R000595",
                eliteSchool: false,
                email: "rubio.senate.gov/public/index.cfm/contact",
                firstName: "Marco",
                lastName: "Rubio",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3041",
                portrait: "fl-marco-rubio",
                senateClass: "Class III",
                state: "Florida",
                website: "rubio.senate.gov",
            },
            {
                address1: "332 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "S000033",
                eliteSchool: true, //Univ of Chicago
                email: "sanders.senate.gov/contact",
                firstName: "Bernard",
                lastName: "Sanders",
                leadershipPosition: null,
                party: "I",
                phone: "(202) 224-5141",
                portrait: "vt-bernie-sanders",
                senateClass: "Class I",
                state: "Vermont",
                website: "sanders.senate.gov",
            },
            {
                address1: "139 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "S001197",
                eliteSchool: true, //Harvard, Yale
                email: "sasse.senate.gov/public/index.cfm/email-ben",
                firstName: "Ben",
                lastName: "Sasse",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4224",
                portrait: "ne-ben-sasse",
                senateClass: "Class II",
                state: "Nebraska",
                website: "sasse.senate.gov",
            },
            {
                address1: "722 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 26, 2012",
                bioguideId: "S001194",
                eliteSchool: false,
                email: "schatz.senate.gov/contact",
                firstName: "Brian",
                lastName: "Schatz",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3934",
                portrait: "hi-brian-schatz",
                senateClass: "Class III",
                state: "Hawaii",
                website: "schatz.senate.gov",
            },
            {
                address1: "322 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1999",
                bioguideId: "S000148",
                eliteSchool: true, //Harvard
                email: "schumer.senate.gov/contact/email-chuck",
                firstName: "Charles E.",
                lastName: "Schumer",
                leadershipPosition: "Democratic Leader",
                party: "D",
                phone: "(202) 224-6542",
                portrait: "ny-chuck-schumer",
                senateClass: "Class III",
                state: "New York",
                website: "schumer.senate.gov",
            },
            {
                address1: "502 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 8, 2019",
                bioguideId: "S001217",
                eliteSchool: false,
                email: "rickscott.senate.gov/contact/contact",
                firstName: "Rick",
                lastName: "Scott",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5274",
                portrait: "fl-rick-scott",
                senateClass: "Class I",
                state: "Florida",
                website: "rickscott.senate.gov",
            },
            {
                address1: "104 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "S001184",
                eliteSchool: false,
                email: "scott.senate.gov/contact/email-me",
                firstName: "Tim",
                lastName: "Scott",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6121",
                portrait: "sc-tim-scott",
                senateClass: "Class III",
                state: "South Carolina",
                website: "scott.senate.gov",
            },
            {
                address1: "506 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "S001181",
                eliteSchool: false,
                email: "shaheen.senate.gov/contact/contact-jeanne",
                firstName: "Jeanne",
                lastName: "Shaheen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2841",
                portrait: "nh-jeanne-shaheen",
                senateClass: "Class II",
                state: "New Hampshire",
                website: "shaheen.senate.gov",
            },
            {
                address1: "304 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1987",
                bioguideId: "S000320",
                eliteSchool: false,
                email: "shelby.senate.gov/public/index.cfm/emailsenatorshelby",
                firstName: "Richard C.",
                lastName: "Shelby",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5744",
                portrait: "al-richard-shelby",
                senateClass: "Class III",
                state: "Alabama",
                website: "shelby.senate.gov",
            },
            {
                address1: "317 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "S001191",
                eliteSchool: false,
                email: "sinema.senate.gov/contact-kyrsten",
                firstName: "Kyrsten",
                lastName: "Sinema",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4521",
                portrait: "az-kyrsten-sinema",
                senateClass: "Class I",
                state: "Arizona",
                website: "sinema.senate.gov",
            },
            {
                address1: "720 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2018",
                bioguideId: "S001203",
                eliteSchool: true, //Stanford, Dartmouth
                email: "smith.senate.gov/contact-tina",
                firstName: "Tina",
                lastName: "Smith",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5641",
                portrait: "mn-tina-smith",
                senateClass: "Class II",
                state: "Minnesota",
                website: "smith.senate.gov",
            },
            {
                address1: "731 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "S000770",
                eliteSchool: false,
                email: "stabenow.senate.gov/contact",
                firstName: "Debbie",
                lastName: "Stabenow",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4822",
                portrait: "mi-debbie-stabenow",
                senateClass: "Class I",
                state: "Michigan",
                website: "stabenow.senate.gov",
            },
            {
                address1: "302 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "S001198",
                eliteSchool: true, //Harvard, Georgetown
                email: "sullivan.senate.gov/contact/email",
                firstName: "Dan",
                lastName: "Sullivan",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3004",
                portrait: "ak-dan-sullivan",
                senateClass: "Class II",
                state: "Alaska",
                website: "sullivan.senate.gov",
            },
            {
                address1: "311 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "T000464",
                eliteSchool: false,
                email: "tester.senate.gov/?p=email_senator",
                firstName: "Jon",
                lastName: "Tester",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2644",
                portrait: "mt-jon-tester",
                senateClass: "Class I",
                state: "Montana",
                website: "tester.senate.gov",
            },
            {
                address1: "511 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2005",
                bioguideId: "T000250",
                eliteSchool: false,
                email: "thune.senate.gov/public/index.cfm/contact",
                firstName: "John",
                lastName: "Thune",
                leadershipPosition: "Whip",
                party: "R",
                phone: "(202) 224-2321",
                portrait: "sd-john-thune",
                senateClass: "Class III",
                state: "South Dakota",
                website: "thune.senate.gov",
            },
            {
                address1: "113 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "T000476",
                eliteSchool: false,
                email: "tillis.senate.gov/public/index.cfm/email-me",
                firstName: "Thom",
                lastName: "Tillis",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6342",
                portrait: "nc-thom-tillis",
                senateClass: "Class II",
                state: "North Carolina",
                website: "tillis.senate.gov",
            },
            {
                address1: "455 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "T000461",
                eliteSchool: true, //Harvard
                email: "toomey.senate.gov/?p=contact",
                firstName: "Patrick J.",
                lastName: "Toomey",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4254",
                portrait: "pa-pat-toomey",
                senateClass: "Class III",
                state: "Pennsylvania",
                website: "toomey.senate.gov",
            },
            {
                address1: "142 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "T000278",
                eliteSchool: false,
                email: "tuberville.senate.gov/contact/contact-form/",
                firstName: "Tommy",
                lastName: "Tuberville",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4124",
                portrait: "al-tommy-tuberville",
                senateClass: "Class II",
                state: "Alabama",
                website: "tuberville.senate.gov",
            },
            {
                address1: "110 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "V000128",
                eliteSchool: true, //Harvard, Georgetown
                email: "vanhollen.senate.gov/contact/email",
                firstName: "Chris",
                lastName: "Van Hollen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4654",
                portrait: "md-chris-van-hollen",
                senateClass: "Class III",
                state: "Maryland",
                website: "vanhollen.senate.gov",
            },
            {
                address1: "703 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "W000805",
                eliteSchool: true, //Harvard
                email: "warner.senate.gov/public/index.cfm?p=Contact",
                firstName: "Mark R.",
                lastName: "Warner",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2023",
                portrait: "va-mark-warner",
                senateClass: "Class II",
                state: "Virginia",
                website: "warner.senate.gov",
            },
            {
                address1: "388 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "W000790",
                eliteSchool: false,
                email: "warnock.senate.gov/contact",
                firstName: "Raphael G.",
                lastName: "Warnock",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3643",
                portrait: "ga-raphael-warnock",
                senateClass: "Class III",
                state: "Georgia",
                website: "warnock.senate.gov",
            },
            {
                address1: "309 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "W000817",
                eliteSchool: false,
                email: "warren.senate.gov/?p=email_senator",
                firstName: "Elizabeth",
                lastName: "Warren",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4543",
                portrait: "ma-elizabeth-warren",
                senateClass: "Class I",
                state: "Massachusetts",
                website: "warren.senate.gov",
            },
            {
                address1: "530 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "W000802",
                eliteSchool: true, //Yale
                email: "whitehouse.senate.gov/contact/email-sheldon",
                firstName: "Sheldon",
                lastName: "Whitehouse",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2921",
                portrait: "ri-sheldon-whitehouse",
                senateClass: "Class I",
                state: "Rhode Island",
                website: "whitehouse.senate.gov",
            },
            {
                address1: "555 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 31, 2007",
                bioguideId: "W000437",
                eliteSchool: false,
                email: "wicker.senate.gov/public/index.cfm/contact",
                firstName: "Roger F.",
                lastName: "Wicker",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6253",
                portrait: "ms-roger-wicker",
                senateClass: "Class I",
                state: "Mississippi",
                website: "wicker.senate.gov",
            },
            {
                address1: "221 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "February 5, 1996",
                bioguideId: "W000779",
                eliteSchool: true, //Stanford
                email: "wyden.senate.gov/contact",
                firstName: "Ron",
                lastName: "Wyden",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5244",
                portrait: "or-ron-wyden",
                senateClass: "Class III",
                state: "Oregon",
                website: "wyden.senate.gov",
            },
            {
                address1: "185 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "Y000064",
                eliteSchool: true, //West Point, Univ of Chicago
                email: "young.senate.gov/contact",
                firstName: "Todd",
                lastName: "Young",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5623",
                portrait: "in-todd-young",
                senateClass: "Class III",
                state: "Indiana",
                website: "young.senate.gov",
            },
        ],
    },
    getters: {
        getAlabama: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Alabama"
            );
        },
        getAlaska: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Alaska"
            );
        },
        getArizona: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Arizona"
            );
        },
        getArkansas: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Arkansas"
            );
        },
        getCalifornia: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "California"
            );
        },
        getColorado: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Colorado"
            );
        },
        getConnecticut: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Connecticut"
            );
        },
        getDelaware: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Delaware"
            );
        },
        getFlorida: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Florida"
            );
        },
        getGeorgia: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Georgia"
            );
        },
        getHawaii: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Hawaii"
            );
        },
        getIdaho: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Idaho"
            );
        },
        getIllinois: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Illinois"
            );
        },
        getIndiana: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Indiana"
            );
        },
        getIowa: (state) => {
            return state.senators.filter((senator) => senator.state === "Iowa");
        },
        getKansas: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Kansas"
            );
        },
        getKentucky: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Kentucky"
            );
        },
        getLouisiana: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Louisiana"
            );
        },
        getMaine: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Maine"
            );
        },
        getMaryland: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Maryland"
            );
        },
        getMassachusetts: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Massachusetts"
            );
        },
        getMichigan: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Michigan"
            );
        },
        getMinnesota: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Minnesota"
            );
        },
        getMississippi: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Mississippi"
            );
        },
        getMissouri: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Missouri"
            );
        },
        getMontana: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Montana"
            );
        },
        getNebraska: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Nebraska"
            );
        },
        getNevada: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Nevada"
            );
        },
        getNewHampshire: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "New Hampshire"
            );
        },
        getNewJersey: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "New Jersey"
            );
        },
        getNewMexico: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "New Mexico"
            );
        },
        getNewYork: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "New York"
            );
        },
        getNorthCarolina: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "North Carolina"
            );
        },
        getNorthDakota: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "North Dakota"
            );
        },
        getOhio: (state) => {
            return state.senators.filter((senator) => senator.state === "Ohio");
        },
        getOklahoma: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Oklahoma"
            );
        },
        getOregon: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Oregon"
            );
        },
        getPennsylvania: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Pennsylvania"
            );
        },
        getRhodeIsland: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Rhode Island"
            );
        },
        getSouthCarolina: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "South Carolina"
            );
        },
        getSouthDakota: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "South Dakota"
            );
        },
        getTennessee: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Tennessee"
            );
        },
        getTexas: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Texas"
            );
        },
        getUtah: (state) => {
            return state.senators.filter((senator) => senator.state === "Utah");
        },
        getVermont: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Vermont"
            );
        },
        getVirginia: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Virginia"
            );
        },
        getWashington: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Washington"
            );
        },
        getWestVirginia: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "West Virginia"
            );
        },
        getWisconsin: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Wisconsin"
            );
        },
        getWyoming: (state) => {
            return state.senators.filter(
                (senator) => senator.state === "Wyoming"
            );
        },
        getClassOne: (state) => {
            return state.senators.filter(
                (senator) => senator.senateClass === "Class I"
            );
        },
        getClassTwo: (state) => {
            return state.senators.filter(
                (senator) => senator.senateClass === "Class II"
            );
        },
        getClassThree: (state) => {
            return state.senators.filter(
                (senator) => senator.senateClass === "Class III"
            );
        },
        getDemocrats: (state) => {
            return state.senators.filter((senator) => senator.party === "D");
        },
        getIndependents: (state) => {
            return state.senators.filter((senator) => senator.party === "I");
        },
        getRepublicans: (state) => {
            return state.senators.filter((senator) => senator.party === "R");
        },
        getLeaders: (state) => {
            return state.senators.filter(
                (senator) => senator.leadershipPosition !== null
            );
        },
    },
    mutations: {},
    actions: {},
    modules: {},
});
