import { createStore } from "vuex";

export default createStore({
    state: {
        senators: [
            {
                address1: "709 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "B001230",
                eliteSchool: true, //Smith
                email: "baldwin.senate.gov/feedback",
                firstName: "Tammy",
                lastName: "Baldwin",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5653",
                portrait: "images/wi-tammy-baldwin.jpg",
                senateClass: "Class I",
                state: "Wisconsin",
                website: "baldwin.senate.gov",
            },
            {
                address1: "307 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "June 25, 2007",
                bioguideId: "B001261",
                eliteSchool: true, //Georgetown
                email: "barrasso.senate.gov/public/index.cfm/contact-form",
                firstName: "John",
                lastName: "Barrasso",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6441",
                portrait: "images/wy-john-barrasso.jpg",
                senateClass: "Class I",
                state: "Wyoming",
                website: "barrasso.senate.gov",
            },
            {
                address1: "261 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 21, 2009",
                bioguideId: "B001267",
                eliteSchool: true, //Yale
                email: "bennet.senate.gov/public/index.cfm/contact",
                firstName: "Michael F.",
                lastName: "Bennet",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5852",
                portrait: "images/co-michael-bennet.jpg",
                senateClass: "Class III",
                state: "Colorado",
                website: "bennet.senate.gov",
            },
            {
                address1: "357 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "B001243",
                eliteSchool: false,
                email: "blackburn.senate.gov/email-me",
                firstName: "Marsha",
                lastName: "Blackburn",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3344",
                portrait: "images/tn-marsha-blackburn.jpg",
                senateClass: "Class I",
                state: "Tennessee",
                website: "blackburn.senate.gov",
            },
            {
                address1: "706 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B001277",
                eliteSchool: true, //Harvard, Yale
                email: "blumenthal.senate.gov/contact",
                firstName: "Richard",
                lastName: "Blumenthal",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2823",
                portrait: "images/ct-richard-blumenthal.jpg",
                senateClass: "Class III",
                state: "Connecticut",
                website: "blumenthal.senate.gov",
            },
            {
                address1: "260 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B000575",
                eliteSchool: false,
                email: "blunt.senate.gov/public/index.cfm/contact-roy",
                firstName: "Roy",
                lastName: "Blunt",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5721",
                portrait: "images/mo-roy-blunt.jpg",
                senateClass: "Class III",
                state: "Missouri",
                website: "blunt.senate.gov",
            },
            {
                address1: "717 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "October 31, 2013",
                bioguideId: "B001288",
                eliteSchool: true, //Stanford, Oxford, Yale
                email: "booker.senate.gov/?p=contact",
                firstName: "Cory A.",
                lastName: "Booker",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3224",
                portrait: "images/nj-cory-booker.jpg",
                senateClass: "Class II",
                state: "New Jersey",
                website: "booker.senate.gov",
            },
            {
                address1: "141 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "B001236",
                eliteSchool: false,
                email: "boozman.senate.gov/public/index.cfm/contact",
                firstName: "John",
                lastName: "Boozman",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4843",
                portrait: "images/ar-john-boozman.jpg",
                senateClass: "Class III",
                state: "Arkansas",
                website: "boozman.senate.gov",
            },
            {
                address1: "404 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "B001310",
                eliteSchool: true, //Harvard
                email: "braun.senate.gov/contact-mike",
                firstName: "Mike",
                lastName: "Braun",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4814",
                portrait: "images/in-mike-braun.jpg",
                senateClass: "Class I",
                state: "Indiana",
                website: "braun.senate.gov",
            },
            {
                address1: "503 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "B000944",
                eliteSchool: true, //Yale
                email: "brown.senate.gov/contact",
                firstName: "Sherrod",
                lastName: "Brown",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2315",
                portrait: "images/oh-sherrod-brown.jpg",
                senateClass: "Class I",
                state: "Ohio",
                website: "brown.senate.gov",
            },
            {
                address1: "217 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2005",
                bioguideId: "B001135",
                eliteSchool: false,
                email: "burr.senate.gov/contact",
                firstName: "Richard",
                lastName: "Burr",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3154",
                portrait: "images/nc-richard-burr.jpg",
                senateClass: "Class III",
                state: "North Carolina",
                website: "burr.senate.gov",
            },
            {
                address1: "511 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "C000127",
                eliteSchool: false,
                email: "cantwell.senate.gov/public/index.cfm/email-maria",
                firstName: "Maria",
                lastName: "Cantwell",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3441",
                portrait: "images/wa-maria-cantwell.jpg",
                senateClass: "Class I",
                state: "Washington",
                website: "cantwell.senate.gov",
            },
            {
                address1: "172 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001047",
                eliteSchool: true, //Duke
                email: "capito.senate.gov/contact/contact-shelley",
                firstName: "Shelley Moore",
                lastName: "Capito",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6472",
                portrait: "images/wv-shelley-moore-capito.jpg",
                senateClass: "Class II",
                state: "West Virginia",
                website: "capito.senate.gov",
            },
            {
                address1: "509 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "C000141",
                eliteSchool: false,
                email: "cardin.senate.gov/contact",
                firstName: "Benjamin L.",
                lastName: "Cardin",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4524",
                portrait: "images/md-benjamin-cardin.jpg",
                senateClass: "Class I",
                state: "Maryland",
                website: "cardin.senate.gov",
            },
            {
                address1: "513 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "C000174",
                eliteSchool: false,
                email: "carper.senate.gov/public/index.cfm/email-senator-carper",
                firstName: "Thomas R.",
                lastName: "Carper",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2441",
                portrait: "images/de-thomas-carper.jpg",
                senateClass: "Class I",
                state: "Delaware",
                website: "carper.senate.gov",
            },
            {
                address1: "393 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "C001070",
                eliteSchool: false,
                email: "casey.senate.gov/contact",
                firstName: "Robert P., Jr.",
                lastName: "Casey",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6324",
                portrait: "images/pa-robert-casey.jpg",
                senateClass: "Class I",
                state: "Pennsylvania",
                website: "casey.senate.gov",
            },
            {
                address1: "520 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001075",
                eliteSchool: false,
                email: "cassidy.senate.gov/contact",
                firstName: "Bill",
                lastName: "Cassidy",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5824",
                portrait: "images/la-bill-cassidy.jpg",
                senateClass: "Class II",
                state: "Louisiana",
                website: "cassidy.senate.gov",
            },
            {
                address1: "413 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "C001035",
                eliteSchool: false,
                email: "collins.senate.gov/contact",
                firstName: "Susan M.",
                lastName: "Collins",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2523",
                portrait: "images/me-susan-collins.jpg",
                senateClass: "Class II",
                state: "Maine",
                website: "collins.senate.gov",
            },
            {
                address1: "218 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 15, 2010",
                bioguideId: "C001088",
                eliteSchool: true, //Amherst, Yale
                email: "coons.senate.gov/contact",
                firstName: "Christopher A.",
                lastName: "Coons",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5042",
                portrait: "images/de-christopher-coons.jpg",
                senateClass: "Class II",
                state: "Delaware",
                website: "coons.senate.gov",
            },
            {
                address1: "517 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 2, 2002",
                bioguideId: "C001056",
                eliteSchool: false,
                email: "cornyn.senate.gov/contact",
                firstName: "John",
                lastName: "Cornyn",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2934",
                portrait: "images/tx-john-cornyn.jpg",
                senateClass: "Class II",
                state: "Texas",
                website: "cornyn.senate.gov",
            },
            {
                address1: "313 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "C001113",
                eliteSchool: false,
                email: "cortezmasto.senate.gov/contact",
                firstName: "Catherine",
                lastName: "Cortez Masto",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3542",
                portrait: "images/nv-catherine-cortez-masto.jpg",
                senateClass: "Class III",
                state: "Nevada",
                website: "cortezmasto.senate.gov",
            },
            {
                address1: "326 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "C001095",
                eliteSchool: true, //Harvard
                email: "cotton.senate.gov/contact/contact-tom",
                firstName: "Tom",
                lastName: "Cotton",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2353",
                portrait: "images/ar-tom-cotton.jpg",
                senateClass: "Class II",
                state: "Arkansas",
                website: "cotton.senate.gov",
            },
            {
                address1: "330 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "C001096",
                eliteSchool: false,
                email: "cramer.senate.gov/contact/contact-kevin",
                firstName: "Kevin",
                lastName: "Cramer",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2043",
                portrait: "images/nd-kevin-cramer.jpg",
                senateClass: "Class I",
                state: "North Dakota",
                website: "cramer.senate.gov",
            },
            {
                address1: "239 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1999",
                bioguideId: "C000880",
                eliteSchool: true, //Harvard
                email: "crapo.senate.gov/contact",
                firstName: "Mike",
                lastName: "Crapo",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6142",
                portrait: "images/id-mike-crapo.jpg",
                senateClass: "Class III",
                state: "Idaho",
                website: "crapo.senate.gov",
            },
            {
                address1: "127A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "C001098",
                eliteSchool: true, //Princeton, Harvard
                email: "cruz.senate.gov/?p=form&id=16",
                firstName: "Ted",
                lastName: "Cruz",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5922",
                portrait: "images/tx-ted-cruz.jpg",
                senateClass: "Class I",
                state: "Texas",
                website: "cruz.senate.gov",
            },
            {
                address1: "320 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "D000618",
                eliteSchool: false,
                email: "daines.senate.gov/connect/email-steve",
                firstName: "Steve",
                lastName: "Daines",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2651",
                portrait: "images/mt-steve-daines.jpg",
                senateClass: "Class II",
                state: "Montana",
                website: "daines.senate.gov",
            },
            {
                address1: "524 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "D000622",
                eliteSchool: false,
                email: "duckworth.senate.gov/content/contact-senator",
                firstName: "Tammy",
                lastName: "Duckworth",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2854",
                portrait: "images/il-tammy-duckworth.jpg",
                senateClass: "Class III",
                state: "Illinois",
                website: "duckworth.senate.gov",
            },
            {
                address1: "711 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "D000563",
                eliteSchool: true, //Georgetown
                email: "durbin.senate.gov/contact",
                firstName: "Richard J.",
                lastName: "Durbin",
                leadershipPosition: "Majority Whip",
                party: "D",
                phone: "(202) 224-2152",
                portrait: "images/il-richard-durbin.jpg",
                senateClass: "Class II",
                state: "Illinois",
                website: "durbin.senate.gov",
            },
            {
                address1: "730 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "E000295",
                eliteSchool: false,
                email: "ernst.senate.gov/public/index.cfm/contact",
                firstName: "Joni",
                lastName: "Ernst",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3254",
                portrait: "images/ia-joni-ernst.jpg",
                senateClass: "Class II",
                state: "Iowa",
                website: "ernst.senate.gov",
            },
            {
                address1: "331 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 10, 1992",
                bioguideId: "F000062",
                eliteSchool: true, //Stanford
                email: "feinstein.senate.gov/public/index.cfm/e-mail-me",
                firstName: "Dianne",
                lastName: "Feinstein",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3841",
                portrait: "images/ca-dianne-feinstein.jpg",
                senateClass: "Class I",
                state: "California",
                website: "feinstein.senate.gov",
            },
            {
                address1: "454 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "F000463",
                eliteSchool: false,
                email: "fischer.senate.gov/public/index.cfm/contact",
                firstName: "Deb",
                lastName: "Fischer",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6551",
                portrait: "images/ne-deb-fischer.jpg",
                senateClass: "Class I",
                state: "Nebraska",
                website: "fischer.senate.gov",
            },
            {
                address1: "478 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 26, 2009",
                bioguideId: "G000555",
                eliteSchool: true, //Dartmouth
                email: "gillibrand.senate.gov/contact/email-me",
                firstName: "Kirsten E.",
                lastName: "Gillibrand",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4451",
                portrait: "images/ny-kirsten-gillibrand.jpg",
                senateClass: "Class I",
                state: "New York",
                website: "gillibrand.senate.gov",
            },
            {
                address1: "290 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2003",
                bioguideId: "G000359",
                eliteSchool: false,
                email: "lgraham.senate.gov/public/index.cfm/e-mail-senator-graham",
                firstName: "Lindsey",
                lastName: "Graham",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5972",
                portrait: "images/sc-lindsey-graham.jpg",
                senateClass: "Class II",
                state: "South Carolina",
                website: "lgraham.senate.gov",
            },
            {
                address1: "135 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1981",
                bioguideId: "G000386",
                eliteSchool: false,
                email: "grassley.senate.gov/contact",
                firstName: "Chuck",
                lastName: "Grassley",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3744",
                portrait: "images/ia-chuck-grassley.jpg",
                senateClass: "Class III",
                state: "Iowa",
                website: "grassley.senate.gov",
            },
            {
                address1: "248 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "H000601",
                eliteSchool: false,
                email: "hagerty.senate.gov/email-me",
                firstName: "Bill",
                lastName: "Hagerty",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4944",
                portrait: "images/tn-bill-hagerty.jpg",
                senateClass: "Class II",
                state: "Tennessee",
                website: "hagerty.senate.gov",
            },
            {
                address1: "324 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "H001076",
                eliteSchool: true, //Brown
                email: "hassan.senate.gov/content/contact-senator",
                firstName: "Margaret Wood",
                lastName: "Hassan",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3324",
                portrait: "images/nh-margaret wood-hassan.jpg",
                senateClass: "Class III",
                state: "New Hampshire",
                website: "hassan.senate.gov",
            },
            {
                address1: "115 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "H001089",
                eliteSchool: true, //Stanford, Yale
                email: "hawley.senate.gov/contact-senator-hawley",
                firstName: "Josh",
                lastName: "Hawley",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6154",
                portrait: "images/mo-josh-hawley.jpg",
                senateClass: "Class I",
                state: "Missouri",
                website: "hawley.senate.gov",
            },
            {
                address1: "303 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "H001046",
                eliteSchool: false,
                email: "heinrich.senate.gov/contact",
                firstName: "Martin",
                lastName: "Heinrich",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5521",
                portrait: "images/nm-martin-heinrich.jpg",
                senateClass: "Class I",
                state: "New Mexico",
                website: "heinrich.senate.gov",
            },
            {
                address1: "374 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "H000273",
                eliteSchool: false,
                email: "hickenlooper.senate.gov/contact",
                firstName: "John W.",
                lastName: "Hickenlooper",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5941",
                portrait: "images/co-john-hickenlooper.jpg",
                senateClass: "Class II",
                state: "Colorado",
                website: "hickenlooper.senate.gov",
            },
            {
                address1: "109 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "H001042",
                eliteSchool: true, //Georgetown
                email: "hirono.senate.gov/contact",
                firstName: "Mazie K.",
                lastName: "Hirono",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6361",
                portrait: "images/hi-mazie-hirono.jpg",
                senateClass: "Class I",
                state: "Hawaii",
                website: "hirono.senate.gov",
            },
            {
                address1: "338 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "H001061",
                eliteSchool: true, //Dartmouth, Northwestern
                email: "hoeven.senate.gov/public/index.cfm/email-the-senator",
                firstName: "John",
                lastName: "Hoeven",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2551",
                portrait: "images/nd-john-hoeven.jpg",
                senateClass: "Class III",
                state: "North Dakota",
                website: "hoeven.senate.gov",
            },
            {
                address1: "702 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "April 9, 2018",
                bioguideId: "H001079",
                eliteSchool: false,
                email: "hydesmith.senate.gov/content/contact-senator",
                firstName: "Cindy",
                lastName: "Hyde-Smith",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5054",
                portrait: "images/ms-cindy-hyde-smith.jpg",
                senateClass: "Class II",
                state: "Mississippi",
                website: "hydesmith.senate.gov",
            },
            {
                address1: "205 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 16, 1994",
                bioguideId: "I000024",
                eliteSchool: false,
                email: "inhofe.senate.gov/contact",
                firstName: "James M.",
                lastName: "Inhofe",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4721",
                portrait: "images/ok-james-inhofe.jpg",
                senateClass: "Class II",
                state: "Oklahoma",
                website: "inhofe.senate.gov",
            },
            {
                address1: "328 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "J000293",
                eliteSchool: false,
                email: "ronjohnson.senate.gov/public/index.cfm/email-the-senator",
                firstName: "Ron",
                lastName: "Johnson",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5323",
                portrait: "images/wi-ron-johnson.jpg",
                senateClass: "Class III",
                state: "Wisconsin",
                website: "ronjohnson.senate.gov",
            },
            {
                address1: "231 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "K000384",
                eliteSchool: true, //Harvard
                email: "kaine.senate.gov/contact",
                firstName: "Tim",
                lastName: "Kaine",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4024",
                portrait: "images/va-tim-kaine.jpg",
                senateClass: "Class I",
                state: "Virginia",
                website: "kaine.senate.gov",
            },
            {
                address1: "516 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 2, 2020",
                bioguideId: "K000377",
                eliteSchool: false,
                email: "kelly.senate.gov",
                firstName: "Mark",
                lastName: "Kelly",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2235",
                portrait: "images/az-mark-kelly.jpg",
                senateClass: "Class III",
                state: "Arizona",
                website: "kelly.senate.gov",
            },
            {
                address1: "416 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "K000393",
                eliteSchool: false,
                email: "kennedy.senate.gov/public/email-me",
                firstName: "John",
                lastName: "Kennedy",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4623",
                portrait: "images/la-john-kennedy.jpg",
                senateClass: "Class III",
                state: "Louisiana",
                website: "kennedy.senate.gov",
            },
            {
                address1: "133 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "K000383",
                eliteSchool: true, //Dartmouth
                email: "king.senate.gov/contact",
                firstName: "Angus S., Jr.",
                lastName: "King",
                leadershipPosition: null,
                party: "I",
                phone: "(202) 224-5344",
                portrait: "images/me-angus-king.jpg",
                senateClass: "Class I",
                state: "Maine",
                website: "king.senate.gov",
            },
            {
                address1: "425 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "K000367",
                eliteSchool: true, //Yale, Univ of Chicago
                email: "klobuchar.senate.gov/public/index.cfm/contact",
                firstName: "Amy",
                lastName: "Klobuchar",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3244",
                portrait: "images/mn-amy-klobuchar.jpg",
                senateClass: "Class I",
                state: "Minnesota",
                website: "klobuchar.senate.gov",
            },
            {
                address1: "316 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "L000575",
                eliteSchool: false,
                email: "lankford.senate.gov/contact/email",
                firstName: "James",
                lastName: "Lankford",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5754",
                portrait: "images/ok-james-lankford.jpg",
                senateClass: "Class III",
                state: "Oklahoma",
                website: "lankford.senate.gov",
            },
            {
                address1: "437 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1975",
                bioguideId: "L000174",
                eliteSchool: true, //Georgetown
                email: "leahy.senate.gov/contact",
                firstName: "Patrick J.",
                lastName: "Leahy",
                leadershipPosition: "President Pro Tempore",
                party: "D",
                phone: "(202) 224-4242",
                portrait: "images/vt-patrick-leahy.jpg",
                senateClass: "Class III",
                state: "Vermont",
                website: "leahy.senate.gov",
            },
            {
                address1: "361A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "L000577",
                eliteSchool: false,
                email: "lee.senate.gov/public/index.cfm/contact",
                firstName: "Mike",
                lastName: "Lee",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5444",
                portrait: "images/ut-mike-lee.jpg",
                senateClass: "Class III",
                state: "Utah",
                website: "lee.senate.gov",
            },
            {
                address1: "498 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "L000570",
                eliteSchool: false,
                email: "lujan.senate.gov/contact",
                firstName: "Ben Ray",
                lastName: "Luján",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6621",
                portrait: "images/nm-ben ray-lujan.jpg",
                senateClass: "Class II",
                state: "New Mexico",
                website: "lujan.senate.gov",
            },
            {
                address1: "124 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "L000571",
                eliteSchool: false,
                email: "lummis.senate.gov/contact/contact-form/",
                firstName: "Cynthia M.",
                lastName: "Lummis",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3424",
                portrait: "images/wy-cynthia-lummis.jpg",
                senateClass: "Class II",
                state: "Wyoming",
                website: "lummis.senate.gov",
            },
            {
                address1: "306 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "November 15, 2010",
                bioguideId: "M001183",
                eliteSchool: false,
                email: "manchin.senate.gov/public/index.cfm/contact-form",
                firstName: "Joe, III",
                lastName: "Manchin",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3954",
                portrait: "images/wv-joe, iii-manchin.jpg",
                senateClass: "Class I",
                state: "West Virginia",
                website: "manchin.senate.gov",
            },
            {
                address1: "255 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "July 16, 2013",
                bioguideId: "M000133",
                eliteSchool: false,
                email: "markey.senate.gov/contact",
                firstName: "Edward J.",
                lastName: "Markey",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2742",
                portrait: "images/ma-edward-markey.jpg",
                senateClass: "Class II",
                state: "Massachusetts",
                website: "markey.senate.gov",
            },
            {
                address1: "479A Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "M001198",
                eliteSchool: false,
                email: "marshall.senate.gov/contact",
                firstName: "Roger",
                lastName: "Marshall",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4774",
                portrait: "images/ks-roger-marshall.jpg",
                senateClass: "Class II",
                state: "Kansas",
                website: "marshall.senate.gov",
            },
            {
                address1: "317 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1985",
                bioguideId: "M000355",
                eliteSchool: false,
                email: "mcconnell.senate.gov/public/index.cfm?p=contact",
                firstName: "Mitch",
                lastName: "McConnell",
                leadershipPosition: "Republican Leader",
                party: "R",
                phone: "(202) 224-2541",
                portrait: "images/ky-mitch-mcconnell.jpg",
                senateClass: "Class II",
                state: "Kentucky",
                website: "mcconnell.senate.gov",
            },
            {
                address1: "528 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 17, 2006",
                bioguideId: "M000639",
                eliteSchool: false,
                email: "menendez.senate.gov/contact",
                firstName: "Robert",
                lastName: "Menendez",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4744",
                portrait: "images/nj-robert-menendez.jpg",
                senateClass: "Class I",
                state: "New Jersey",
                website: "menendez.senate.gov",
            },
            {
                address1: "531 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "M001176",
                eliteSchool: true, //Stanford, Princeton
                email: "merkley.senate.gov/contact",
                firstName: "Jeff",
                lastName: "Merkley",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3753",
                portrait: "images/or-jeff-merkley.jpg",
                senateClass: "Class II",
                state: "Oregon",
                website: "merkley.senate.gov",
            },
            {
                address1: "521 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "M000934",
                eliteSchool: false,
                email: "moran.senate.gov/public/index.cfm/e-mail-jerry",
                firstName: "Jerry",
                lastName: "Moran",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6521",
                portrait: "images/ks-jerry-moran.jpg",
                senateClass: "Class III",
                state: "Kansas",
                website: "moran.senate.gov",
            },
            {
                address1: "522 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 20, 2002",
                bioguideId: "M001153",
                eliteSchool: true, //Georgetown
                email: "murkowski.senate.gov/public/index.cfm/contact",
                firstName: "Lisa",
                lastName: "Murkowski",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6665",
                portrait: "images/ak-lisa-murkowski.jpg",
                senateClass: "Class III",
                state: "Alaska",
                website: "murkowski.senate.gov",
            },
            {
                address1: "136 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "M001169",
                eliteSchool: true, //Williams
                email: "murphy.senate.gov/contact",
                firstName: "Christopher",
                lastName: "Murphy",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4041",
                portrait: "images/ct-christopher-murphy.jpg",
                senateClass: "Class I",
                state: "Connecticut",
                website: "murphy.senate.gov",
            },
            {
                address1: "154 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1993",
                bioguideId: "M001111",
                eliteSchool: false,
                email: "murray.senate.gov/write-to-patty/",
                firstName: "Patty",
                lastName: "Murray",
                leadershipPosition: "Assistant Democratic Leader",
                party: "D",
                phone: "(202) 224-2621",
                portrait: "images/wa-patty-murray.jpg",
                senateClass: "Class III",
                state: "Washington",
                website: "murray.senate.gov",
            },
            {
                address1: "455 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "O000174",
                eliteSchool: true, //Georgetown, London School of Econ
                email: "ossoff.senate.gov/contact-us/",
                firstName: "Jon",
                lastName: "Ossoff",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3521",
                portrait: "images/ga-jon-ossoff.jpg",
                senateClass: "Class II",
                state: "Georgia",
                website: "ossoff.senate.gov",
            },
            {
                address1: "112 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "P000145",
                eliteSchool: true, //MIT
                email: "padilla.senate.gov/contact",
                firstName: "Alex",
                lastName: "Padilla",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3553",
                portrait: "images/ca-alex-padilla.jpg",
                senateClass: "Class III",
                state: "California",
                website: "padilla.senate.gov",
            },
            {
                address1: "167 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "P000603",
                eliteSchool: true, //Duke
                email: "paul.senate.gov/connect/email-rand",
                firstName: "Rand",
                lastName: "Paul",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4343",
                portrait: "images/ky-rand-paul.jpg",
                senateClass: "Class III",
                state: "Kentucky",
                website: "paul.senate.gov",
            },
            {
                address1: "724 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "P000595",
                eliteSchool: false,
                email: "peters.senate.gov/contact/email-gary",
                firstName: "Gary C.",
                lastName: "Peters",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6221",
                portrait: "images/mi-gary-peters.jpg",
                senateClass: "Class II",
                state: "Michigan",
                website: "peters.senate.gov",
            },
            {
                address1: "448 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "P000449",
                eliteSchool: true, //Dartmouth
                email: "portman.senate.gov/public/index.cfm/contact?p=contact-form",
                firstName: "Rob",
                lastName: "Portman",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3353",
                portrait: "images/oh-rob-portman.jpg",
                senateClass: "Class III",
                state: "Ohio",
                website: "portman.senate.gov",
            },
            {
                address1: "728 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1997",
                bioguideId: "R000122",
                eliteSchool: true, //West Point, Harvard
                email: "reed.senate.gov/contact",
                firstName: "Jack",
                lastName: "Reed",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4642",
                portrait: "images/ri-jack-reed.jpg",
                senateClass: "Class II",
                state: "Rhode Island",
                website: "reed.senate.gov",
            },
            {
                address1: "483 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "R000584",
                eliteSchool: false,
                email: "risch.senate.gov/public/index.cfm?p=Email",
                firstName: "James E.",
                lastName: "Risch",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-2752",
                portrait: "images/id-james-risch.jpg",
                senateClass: "Class II",
                state: "Idaho",
                website: "risch.senate.gov",
            },
            {
                address1: "354 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "R000615",
                eliteSchool: true, //Harvard
                email: "romney.senate.gov/contact-senator-romney",
                firstName: "Mitt",
                lastName: "Romney",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5251",
                portrait: "images/ut-mitt-romney.jpg",
                senateClass: "Class I",
                state: "Utah",
                website: "romney.senate.gov",
            },
            {
                address1: "713 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "R000608",
                eliteSchool: false,
                email: "rosen.senate.gov/contact_jacky",
                firstName: "Jacky",
                lastName: "Rosen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-6244",
                portrait: "images/nv-jacky-rosen.jpg",
                senateClass: "Class I",
                state: "Nevada",
                website: "rosen.senate.gov",
            },
            {
                address1: "716 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "R000605",
                eliteSchool: false,
                email: "rounds.senate.gov/contact/email-mike",
                firstName: "Mike",
                lastName: "Rounds",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5842",
                portrait: "images/sd-mike-rounds.jpg",
                senateClass: "Class II",
                state: "South Dakota",
                website: "rounds.senate.gov",
            },
            {
                address1: "284 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "R000595",
                eliteSchool: false,
                email: "rubio.senate.gov/public/index.cfm/contact",
                firstName: "Marco",
                lastName: "Rubio",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3041",
                portrait: "images/fl-marco-rubio.jpg",
                senateClass: "Class III",
                state: "Florida",
                website: "rubio.senate.gov",
            },
            {
                address1: "332 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "S000033",
                eliteSchool: true, //Univ of Chicago
                email: "sanders.senate.gov/contact",
                firstName: "Bernard",
                lastName: "Sanders",
                leadershipPosition: null,
                party: "I",
                phone: "(202) 224-5141",
                portrait: "images/vt-bernard-sanders.jpg",
                senateClass: "Class I",
                state: "Vermont",
                website: "sanders.senate.gov",
            },
            {
                address1: "139 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "S001197",
                eliteSchool: true, //Harvard, Yale
                email: "sasse.senate.gov/public/index.cfm/email-ben",
                firstName: "Ben",
                lastName: "Sasse",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4224",
                portrait: "images/ne-ben-sasse.jpg",
                senateClass: "Class II",
                state: "Nebraska",
                website: "sasse.senate.gov",
            },
            {
                address1: "722 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 26, 2012",
                bioguideId: "S001194",
                eliteSchool: false,
                email: "schatz.senate.gov/contact",
                firstName: "Brian",
                lastName: "Schatz",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3934",
                portrait: "images/hi-brian-schatz.jpg",
                senateClass: "Class III",
                state: "Hawaii",
                website: "schatz.senate.gov",
            },
            {
                address1: "322 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1999",
                bioguideId: "S000148",
                eliteSchool: true, //Harvard
                email: "schumer.senate.gov/contact/email-chuck",
                firstName: "Charles E.",
                lastName: "Schumer",
                leadershipPosition: "Democratic Leader",
                party: "D",
                phone: "(202) 224-6542",
                portrait: "images/ny-charles-schumer.jpg",
                senateClass: "Class III",
                state: "New York",
                website: "schumer.senate.gov",
            },
            {
                address1: "502 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 8, 2019",
                bioguideId: "S001217",
                eliteSchool: false,
                email: "rickscott.senate.gov/contact/contact",
                firstName: "Rick",
                lastName: "Scott",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5274",
                portrait: "images/fl-rick-scott.jpg",
                senateClass: "Class I",
                state: "Florida",
                website: "rickscott.senate.gov",
            },
            {
                address1: "104 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "S001184",
                eliteSchool: false,
                email: "scott.senate.gov/contact/email-me",
                firstName: "Tim",
                lastName: "Scott",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6121",
                portrait: "images/sc-tim-scott.jpg",
                senateClass: "Class III",
                state: "South Carolina",
                website: "scott.senate.gov",
            },
            {
                address1: "506 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "S001181",
                eliteSchool: false,
                email: "shaheen.senate.gov/contact/contact-jeanne",
                firstName: "Jeanne",
                lastName: "Shaheen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2841",
                portrait: "images/nh-jeanne-shaheen.jpg",
                senateClass: "Class II",
                state: "New Hampshire",
                website: "shaheen.senate.gov",
            },
            {
                address1: "304 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 1987",
                bioguideId: "S000320",
                eliteSchool: false,
                email: "shelby.senate.gov/public/index.cfm/emailsenatorshelby",
                firstName: "Richard C.",
                lastName: "Shelby",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5744",
                portrait: "images/al-richard-shelby.jpg",
                senateClass: "Class III",
                state: "Alabama",
                website: "shelby.senate.gov",
            },
            {
                address1: "317 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2019",
                bioguideId: "S001191",
                eliteSchool: false,
                email: "sinema.senate.gov/contact-kyrsten",
                firstName: "Kyrsten",
                lastName: "Sinema",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4521",
                portrait: "images/az-kyrsten-sinema.jpg",
                senateClass: "Class I",
                state: "Arizona",
                website: "sinema.senate.gov",
            },
            {
                address1: "720 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2018",
                bioguideId: "S001203",
                eliteSchool: true, //Stanford, Dartmouth
                email: "smith.senate.gov/contact-tina",
                firstName: "Tina",
                lastName: "Smith",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5641",
                portrait: "images/mn-tina-smith.jpg",
                senateClass: "Class II",
                state: "Minnesota",
                website: "smith.senate.gov",
            },
            {
                address1: "731 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2001",
                bioguideId: "S000770",
                eliteSchool: false,
                email: "stabenow.senate.gov/contact",
                firstName: "Debbie",
                lastName: "Stabenow",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4822",
                portrait: "images/mi-debbie-stabenow.jpg",
                senateClass: "Class I",
                state: "Michigan",
                website: "stabenow.senate.gov",
            },
            {
                address1: "302 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "S001198",
                eliteSchool: true, //Harvard, Georgetown
                email: "sullivan.senate.gov/contact/email",
                firstName: "Dan",
                lastName: "Sullivan",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-3004",
                portrait: "images/ak-dan-sullivan.jpg",
                senateClass: "Class II",
                state: "Alaska",
                website: "sullivan.senate.gov",
            },
            {
                address1: "311 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "T000464",
                eliteSchool: false,
                email: "tester.senate.gov/?p=email_senator",
                firstName: "Jon",
                lastName: "Tester",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2644",
                portrait: "images/mt-jon-tester.jpg",
                senateClass: "Class I",
                state: "Montana",
                website: "tester.senate.gov",
            },
            {
                address1: "511 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2005",
                bioguideId: "T000250",
                eliteSchool: false,
                email: "thune.senate.gov/public/index.cfm/contact",
                firstName: "John",
                lastName: "Thune",
                leadershipPosition: "Whip",
                party: "R",
                phone: "(202) 224-2321",
                portrait: "images/sd-john-thune.jpg",
                senateClass: "Class III",
                state: "South Dakota",
                website: "thune.senate.gov",
            },
            {
                address1: "113 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2015",
                bioguideId: "T000476",
                eliteSchool: false,
                email: "tillis.senate.gov/public/index.cfm/email-me",
                firstName: "Thom",
                lastName: "Tillis",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6342",
                portrait: "images/nc-thom-tillis.jpg",
                senateClass: "Class II",
                state: "North Carolina",
                website: "tillis.senate.gov",
            },
            {
                address1: "455 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2011",
                bioguideId: "T000461",
                eliteSchool: true, //Harvard
                email: "toomey.senate.gov/?p=contact",
                firstName: "Patrick J.",
                lastName: "Toomey",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4254",
                portrait: "images/pa-patrick-toomey.jpg",
                senateClass: "Class III",
                state: "Pennsylvania",
                website: "toomey.senate.gov",
            },
            {
                address1: "142 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2021",
                bioguideId: "T000278",
                eliteSchool: false,
                email: "tuberville.senate.gov/contact/contact-form/",
                firstName: "Tommy",
                lastName: "Tuberville",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-4124",
                portrait: "images/al-tommy-tuberville.jpg",
                senateClass: "Class II",
                state: "Alabama",
                website: "tuberville.senate.gov",
            },
            {
                address1: "110 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "V000128",
                eliteSchool: true, //Harvard, Georgetown
                email: "vanhollen.senate.gov/contact/email",
                firstName: "Chris",
                lastName: "Van Hollen",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4654",
                portrait: "images/md-chris-van hollen.jpg",
                senateClass: "Class III",
                state: "Maryland",
                website: "vanhollen.senate.gov",
            },
            {
                address1: "703 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2009",
                bioguideId: "W000805",
                eliteSchool: true, //Harvard
                email: "warner.senate.gov/public/index.cfm?p=Contact",
                firstName: "Mark R.",
                lastName: "Warner",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2023",
                portrait: "images/va-mark-warner.jpg",
                senateClass: "Class II",
                state: "Virginia",
                website: "warner.senate.gov",
            },
            {
                address1: "388 Russell Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 20, 2021",
                bioguideId: "W000790",
                eliteSchool: false,
                email: "warnock.senate.gov/contact",
                firstName: "Raphael G.",
                lastName: "Warnock",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-3643",
                portrait: "images/ga-raphael-warnock.jpg",
                senateClass: "Class III",
                state: "Georgia",
                website: "warnock.senate.gov",
            },
            {
                address1: "309 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2013",
                bioguideId: "W000817",
                eliteSchool: false,
                email: "warren.senate.gov/?p=email_senator",
                firstName: "Elizabeth",
                lastName: "Warren",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-4543",
                portrait: "images/ma-elizabeth-warren.jpg",
                senateClass: "Class I",
                state: "Massachusetts",
                website: "warren.senate.gov",
            },
            {
                address1: "530 Hart Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2007",
                bioguideId: "W000802",
                eliteSchool: true, //Yale
                email: "whitehouse.senate.gov/contact/email-sheldon",
                firstName: "Sheldon",
                lastName: "Whitehouse",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-2921",
                portrait: "images/ri-sheldon-whitehouse.jpg",
                senateClass: "Class I",
                state: "Rhode Island",
                website: "whitehouse.senate.gov",
            },
            {
                address1: "555 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "December 31, 2007",
                bioguideId: "W000437",
                eliteSchool: false,
                email: "wicker.senate.gov/public/index.cfm/contact",
                firstName: "Roger F.",
                lastName: "Wicker",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-6253",
                portrait: "images/ms-roger-wicker.jpg",
                senateClass: "Class I",
                state: "Mississippi",
                website: "wicker.senate.gov",
            },
            {
                address1: "221 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "February 5, 1996",
                bioguideId: "W000779",
                eliteSchool: true, //Stanford
                email: "wyden.senate.gov/contact",
                firstName: "Ron",
                lastName: "Wyden",
                leadershipPosition: null,
                party: "D",
                phone: "(202) 224-5244",
                portrait: "images/or-ron-wyden.jpg",
                senateClass: "Class III",
                state: "Oregon",
                website: "wyden.senate.gov",
            },
            {
                address1: "185 Dirksen Senate Office Building",
                address2: "Washington DC 20510",
                assumedOffice: "January 3, 2017",
                bioguideId: "Y000064",
                eliteSchool: true, //West Point, Univ of Chicago
                email: "young.senate.gov/contact",
                firstName: "Todd",
                lastName: "Young",
                leadershipPosition: null,
                party: "R",
                phone: "(202) 224-5623",
                portrait: "images/in-todd-young.jpg",
                senateClass: "Class III",
                state: "Indiana",
                website: "young.senate.gov",
            },
        ],
    },
    getters: {
        getStates: (state) => {
            return state.senators.map((senator) => {
                return {
                    fullName: senator.firstName + senator.lastName,
                    hState: senator.state,
                };
            });
        },
        getClasses: (state) => {
            return state.senators.map((senator) => {
                return {
                    fullName: senator.firstName + senator.lastName,
                    sClass: senator.senateClass,
                };
            });
        },
        getParties: (state) => {
            return state.senators.map((senator) => {
                return {
                    fullName: senator.firstName + senator.lastName,
                    sParty: senator.party,
                };
            });
        },
        getLeaders: (state) => {
            return state.senators.map((senator) => {
                return {
                    fullName: senator.firstName + senator.lastName,
                    lPosition: senator.leadershipPosition,
                };
            });
        },
    },
    mutations: {},
    actions: {},
    modules: {},
});
